version: 2

references:
  working_directory: &working_directory
    ~/workspace/code
  node_container: &node_container
   docker:
     - image: circleci/node:10.13.0-stretch
   working_directory: *working_directory

jobs:
  build:
    <<: *node_container
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Build
          command: yarn build

  test:
    <<: *node_container
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Yarn Test
          command: yarn test:unit